### ISSUE TITLE
恭喜恭喜,收藏路径有了,现在高效多了.

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#14]
如果选择模板这个也可以像收藏的路径一样摆出来就更方便了.如果能再加一个预设就选中其中一个模板就更高效了.

**Comment by 277383761** [comment]
![image](https://user-images.githubusercontent.com/49450669/173227262-ce6991be-f2f3-4bfc-83bc-eaf6edfa6263.png)
实在是太方便了.不用像从前一样点击点击再点击选路径了.

**Comment by FleyX** [comment]
谢谢
