### ISSUE TITLE
现在老好用了.就是能否更激进一些.

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#15]
现在选择S1下面的文件后,再选择一次自动识别季号的模板就能批量命名了.
但如果这个剧有N季的话.比如S1 S2 S3 S4 S5 S....这么多文件夹,每个都要这样操作一次感觉很没效率.
有没有办法添加上级文件夹目录,如选择S1至S5这么多文件夹同时选中,然后批量命名S目录下的文件.

**Comment by FleyX** [comment]
在 2022年7月4日，19:22，277383761 ***@***.***> 写道：
可以考虑
﻿

现在选择S1下面的文件后,再选择一次自动识别季号的模板就能批量命名了.
但如果这个剧有N季的话.比如S1 S2 S3 S4 S5 S....这么多文件夹,每个都要这样操作一次感觉很没效率.
有没有办法添加上级文件夹目录,如选择S1至S5这么多文件夹同时选中,然后批量命名S目录下的文件.

**Comment by FleyX** [comment]
这个功能，偏离通用重命名太多了，不会实现
