### ISSUE TITLE
自动监控某文件夹运行

### ISSUE THREAD

**Issue by ashlovepink** [FleyX/open-renamer#21]
能否自动运行，并且定期执行批量操作。

**Comment by 277383761** [comment]
> 能否自动运行，并且定期执行批量操作。

这个renamer目前我用做了手动批量电视剧名使用了.我也给作者提过希望弄出这类功能,但作者可能忙吧,你若想全自动的话可以使用nastool来做

**Comment by FleyX** [comment]
自动运行适配起来过于繁杂了，有这个需求的还是用nastool吧
