### ISSUE TITLE
又是我,哈哈

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#23]
![QQ20221202-103538@2x](https://user-images.githubusercontent.com/49450669/205203298-5b837a6c-0589-40fc-a35c-970142dea443.png)
这次的更新很棒很赞,而且支持了过滤srt与ass字幕的功能.现在我只须用一个模板就能摆平视频与字幕的批量命名了,而且可以设置默认模板功能.很方便.效率又提高了不少.
还有两个效率不高之处就是左下角这里的多选源文件以后无法上下移动位置.我是特地搞了几个无法正常排序的文件测试.
还有就是srt字幕文件与视频文件在一起的时候.srt也会占用一个序列号引起了视频文件序列对不上了.
哈哈,如果能从源文件中检测并自动提取集数就爽了.比如我这里有一个视频是第15集的,但现在只能按顺序排下来,15被改成了S1E06集了.这种场景平时也无所谓,有时候100集的电视剧,中间缺一集的时候,这批量命名下去就会全部错位一个序列号.很危险.

**Comment by FleyX** [comment]
1. 多选上下移动可以加上
2. 字幕文件，视频文件不会区别对待，设计的是一次只处理一类文件
3. 准备在自动识别里加一个集数识别

另外目前正在开发集成qbittorrent下载功能，创建任务时设置好各种参数，下载完毕后自动转移到目标文件夹，并重命名

**Comment by FleyX** [comment]
功能已增加，切换到1.2版本镜像即可

**Comment by 277383761** [comment]
> 功能已增加，切换到1.2版本镜像即可

实在是太伟大了.太牛逼,太刺激了.一个模板同时解决所有电视剧视频+字幕的全部了.而且也可以无视排序了
![QQ20221204-091811@2x](https://user-images.githubusercontent.com/49450669/205469450-15a0c0fd-b62b-480d-82e4-ca8cf6704a2e.png)

**Comment by 277383761** [comment]
现在只剩下一个要求了.就是能添加多季的S1 S2 S3这样的文件夹,然后批量命名.不然遇上有10多季的电视剧时效率跟不上.哈

**Comment by 277383761** [comment]
还有一个想法,一般的剧都只有一季.但是有时候上级目录也不存在S1这样的文件夹时,希望再增加一个选项当没有季文件夹默认当第一季来处理,多出这么一个选项提供,当有检测到S2之类的才用S2识别,这样我就又能减少一步手动创建上级S1目录的操作了.效率又提高了

**Comment by 277383761** [comment]
这工具若是上级自动创建一个S1文件夹,就更好了.哈哈哈.

**Comment by 277383761** [comment]
看来还有点点难度.还要加一个判断
![QQ20221204-163706@2x](https://user-images.githubusercontent.com/49450669/205481600-404fb4c2-487d-479c-8765-e7cacac19788.png)

**Comment by FleyX** [comment]
重新pull 1.2版本，已经加上了这个的处理逻辑

> 看来还有点点难度.还要加一个判断 ![QQ20221204-163706@2x](https://user-images.githubusercontent.com/49450669/205481600-404fb4c2-487d-479c-8765-e7cacac19788.png)

**Comment by 277383761** [comment]
嗯,这个解决了.
![截屏2022-12-05 上午8 19 25](https://user-images.githubusercontent.com/49450669/205524826-9dabd17b-b986-453c-a6bf-86a63dd2544b.png)
