### ISSUE TITLE
命名过的文件,再次命名时,会提示异常

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#24]
![image](https://user-images.githubusercontent.com/49450669/208231135-699a90ec-5dce-460d-a02b-de15f4f25acb.png)

**Comment by 277383761** [comment]
因为有些剧还在更新中.所以这种情况出现的频率很高.往往只须命名更新的几集.

**Comment by FleyX** [comment]
已修复，重新拉取latest
