### ISSUE TITLE
哈哈哈.好用

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#25]
今天闲着无聊在clouddrive的群里发了你的批量命名工具,我截了个视频发群里,都说求关键字想安装.我可以推广你的工具吗?
批量命名演示.mp4
https://www.aliyundrive.com/s/dowS5zSN7RY
如果能更高效一点就更好了.可以同时多季一起批量命名.就不用一次一次的清除已选再全新选择文件列表

**Comment by FleyX** [comment]
可以的，欢迎推广。后面新增文件可以直接勾选文件夹添加

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: 277383761 ***@***.***>
Sent: Saturday, February 18, 2023 6:21:05 PM
To: FleyX/open-renamer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FleyX/open-renamer] 哈哈哈.好用 (Issue #25)


今天闲着无聊在clouddrive的群里发了你的批量命名工具,我截了个视频发群里,都说求关键字想安装.我可以推广你的工具吗?
批量命名演示.mp4
https://www.aliyundrive.com/s/dowS5zSN7RY
如果能更高效一点就更好了.可以同时多季一起批量命名.就不用一次一次的清除已选再全新选择文件列表

―

**Comment by 277383761** [comment]
竟然已经反馈了,再反馈一条吧,内个集数宽度希望自动按实际文件数决定吧.一般的电视剧都是一百集以内默认预设2位数...如果遇到超过100集的,希望自动变成3位数.如S1E099 S1E100 这里的99自动变099.
![image](https://user-images.githubusercontent.com/49450669/219855802-c3a6ebd6-1b6b-4798-b836-e85787bd9b57.png)
因为当前模板做好了是2位数的.遇到了100集的就前面还是2位,百集开始是三位.这样显的不够整齐.哈

**Comment by 277383761** [comment]
> 

如果支持直接选择文件夹添加的话.那就更香了.但由于文件夹有时候存在一些非视频非字幕的文件,比如广告类的东西,能否做个功能可以自动过滤,或者在这个位置弄一个按钮可以点击直接删除真实文件.
![image](https://user-images.githubusercontent.com/49450669/219856501-8faab024-4a11-47df-9bc5-dc392c6b8f88.png)
哈哈,我的要求是挺多的.都是打磨细节.哈哈.因为经常用手机转存别人的网盘文件,所以经常会带有一些广告类的非视频文件.挺烦人的.如果你提供一键清除非视频非字幕文件更佳.直接把广告源文件给删除都行

**Comment by FleyX** [comment]
已发布1.3更新版本，更新内容见：[1.3更新](https://blog.fleyx.com/blog/detail/20221130/#13)
