### ISSUE TITLE
遇到一个命名的硬茬

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#26]
![截屏2023-02-20 上午9 34 40](https://user-images.githubusercontent.com/49450669/219989847-8dda0d3f-f7e7-4c37-a20d-888c805a739c.png)
这个所有被集数识别成了4K的4

**Comment by 277383761** [comment]
又遇到一个自动识别的硬❌
![截屏2023-02-23 下午9 13 23](https://user-images.githubusercontent.com/49450669/220916786-eb0c248e-cbdb-4853-b1b3-2a7fd7babb92.png)

**Comment by FleyX** [comment]
已发布1.3更新版本，更新内容见：[1.3更新](https://blog.fleyx.com/blog/detail/20221130/#13)
