### ISSUE TITLE
新版变成了每次都要输入密码,有点麻烦

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#27]
哈哈,从前内样好,只有换了一台新设备才须要输入密码

**Comment by 277383761** [comment]
每次刷新都会提示如上弹窗
![image](https://user-images.githubusercontent.com/49450669/223886592-9194ecec-6c19-483c-afdb-598353b563c8.png)

**Comment by 277383761** [comment]
有时候如果点击了一键选择按钮,但又想删除标记时,比较麻烦.或者再来一个全选的按钮会不会更理想.哈哈

**Comment by FleyX** [comment]
> 每次刷新都会提示如上弹窗 ![image](https://user-images.githubusercontent.com/49450669/223886592-9194ecec-6c19-483c-afdb-598353b563c8.png)

等会儿修复下

**Comment by FleyX** [comment]
> 有时候如果点击了一键选择按钮,但又想删除标记时,比较麻烦.或者再来一个全选的按钮会不会更理想.哈哈

这个把反选功能改为全选/不选

**Comment by FleyX** [comment]
更新latest或者1.3.1
