### ISSUE TITLE
可否给个完整的操作说明

### ISSUE THREAD

**Issue by caeser2** [FleyX/open-renamer#28]
试了几次，总是搞不对，上面的选项似乎选不选都没有啥影响？

**Comment by caeser2** [comment]
哦，原来是不支持tmm默认重命名的季名，建议大佬支持一下Season.1，Season.01之类的规则，首字母可大可小，中间有.

**Comment by FleyX** [comment]
最新版添加了一个预设模板，可以用这个试试
如果没有推荐模板，需要更新服务到最新版本。
![image](https://user-images.githubusercontent.com/29558551/229400886-2f08f758-a7db-497f-b26e-965578e3fe59.png)
能够识别的剧集通常为如下目录层级：
剧名：
    季号(比如：season 01;s01):
        集（比如01.mp4;02.mp4）

**Comment by FleyX** [comment]
> 哦，原来是不支持tmm默认重命名的季名，建议大佬支持一下Season.1，Season.01之类的规则，首字母可大可小，中间有.

没问题，后续会更新支持

**Comment by FleyX** [comment]
已支持，更新latest版本或者切换到1.4版本
