### ISSUE TITLE
很赞,数字可以完美识别,但是中文一二三不能哈哈

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#29]
![image](https://user-images.githubusercontent.com/49450669/230838063-e05cac86-f295-458c-af9f-a101a1b1c309.png)
![截屏2023-04-10 下午2 06 52](https://user-images.githubusercontent.com/49450669/230838084-604def45-7e23-412a-8379-f3113b6120ce.png)

**Comment by 277383761** [comment]
第1季,第一季.前者完美,后者不完美.总之比之前只识别S1 S01之类的更香了.

**Comment by caeser2** [comment]
大佬考虑下season.1，season.02这样的格式撒

**Comment by FleyX** [comment]
> 大佬考虑下season.1，season.02这样的格式撒，已更新到1.4，但还是不行
![image](https://user-images.githubusercontent.com/29558551/231740926-6774ef9f-befb-40b7-8409-7da8de141ea0.png)
![image](https://user-images.githubusercontent.com/29558551/231741173-04128b9f-5516-48ae-8d09-572798948972.png)
这种目前已经支持
