### ISSUE TITLE
嘿嘿,又是我来啦

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#3]
上一个数字序列号排列问题解决了,辛苦你啦
这次希望加入一个新功能,当然此功能您可做可不做.我主要是给emby批量命名电视剧用的.
如果能指定某个文件夹带智能检测功能,比如检测到S01或S1或Season x的文件夹内的文件自动批量命名成
S1E01 S1E02 S1E03...

如果检测到有S2的文件夹下,自动批量命名成S2E01 S2E02 S2E03...

虽然我现在用模板可以手动迅速的点击一下就完成,但是更希望带检测功能会更有效率.

**Comment by FleyX** [comment]
可以的，有空弄下。
我自己用的过程中也觉得好几季一起重命名时改季号比较麻烦。
