### ISSUE TITLE
序列化功能可否增加一个区分扩展名

### ISSUE THREAD

**Issue by caeser2** [FleyX/open-renamer#30]
比如1.mkv,1.ass,1.nfo，现在序列化完会变成1.mkv,2.ass,3.nfo，如果能按扩展名分类序列化就更方便啦

**Comment by FleyX** [comment]
1.5版本已增加
![image](https://user-images.githubusercontent.com/29558551/231769216-902abf7b-3139-4b64-a54c-97b115851bbd.png)
