### ISSUE TITLE
哈哈,工具已经非常满意了.最后提一个要求

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#32]
希望可以弄个监测功能.监测到此目录下有文件时.就自动批量按首选模板命名.
如果不存在S1或S01目录之类的,希望可以自动生成一个这样的目录.
源始:/电视剧被监测目录/终末的后宫第一季/第一集..第二集...第三集
目标:/电视剧命名完成/终末的后宫 (2021)/S1/终末的后宫 - S1E01 ...终末的后宫 - S1E02 ....终末的后宫 - S1E03
不知道能否实现,真的是懒到想无人值守了,哈哈.不过想识别到(2021)估计还得接入tmdb

**Comment by 277383761** [comment]
如果如上可以实现,那我还有更变态的.喜欢用电视剧名的首字母放在不同的英文字母内.不知道能否实现
![image](https://user-images.githubusercontent.com/49450669/233835254-6261b83f-30c1-4024-9903-596db3fd31fc.png)
![image](https://user-images.githubusercontent.com/49450669/233835272-3d1ac4c1-92be-4aa5-9370-7ea01d174b1c.png)

**Comment by 277383761** [comment]
你的工具目前很适合手动批量命名,而nastool适合全自动批量命名.
![image](https://user-images.githubusercontent.com/49450669/234452215-c72c9f3a-62e2-44a3-b717-66fb42335e5d.png)

**Comment by 277383761** [comment]
nastool的流程大概是这样的.
搜索资源--索引资源--下载资源--命名资源--刮削资源--触发emby类媒体app扫描--入库成功
如果是网盘上的话:转存资源--被监控目录自动命名并移动文件至媒体目录下--触发emby媒体扫描--入库成功

目前用你的工具大部分时间用于手动批量新转存的电视剧.而nt大部分用于自动.我录制一下nt的视频,您瞧瞧看,主要是nastool配置过程非常麻烦,我配置过一回都不想再配置了.但是最终实现的效果非常理想
https://www.aliyundrive.com/s/bGUsVKBbKbc

**Comment by FleyX** [comment]
这个太复杂了，而且对我个人来说没有太大的用处，所以暂时没有这方面的开发计划。
如果需要此项功能的人很多，可以考虑实现
