### ISSUE TITLE
希望增加替换字符串规则

### ISSUE THREAD

**Issue by Alano-i** [FleyX/open-renamer#33]
工具很好用，感谢作者！

在使用过程中发现经常需要手动替换一些字符串，虽然能通过 `删除`  `插入` 等规则实现，但是有些繁琐，如果能直接通过替换字符串就要方便的多。

比如下面修改文件名，一顿操作猛如虎，不如一句替换规则来得舒服。

所以希望能增加 `替换字符串` 规则

<img width="795" alt="image" src="https://user-images.githubusercontent.com/68833595/236629097-0221828e-33a3-45c6-8fe8-5a263a07f61d.png">

**Comment by FleyX** [comment]
可以的

**Comment by Alano-i** [comment]
感谢，期待！

**Comment by Alano-i** [comment]
可以正常替换了，谢谢大佬！
美中不足的就是预览太长了会粘在一起，加个调左右预览文字显示宽度（类似Excel表格）或者换行时增加列表高度也许能行，不过这都算是锦上添花了，目前功能完美。

<img width="1388" alt="image" src="https://github.com/FleyX/open-renamer/assets/68833595/078cbb24-100f-4f33-b055-214697150947">

**Comment by FleyX** [comment]
1.6.1修复
