### ISSUE TITLE
偶尔有些剧不含S文件夹下面依旧取了父父级的标题

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#37]
最近由于整理一套mp3,所以不用划季的,就没创建S1 S01之类的文件夹.批量命名时,大部分都会只取父级标题,但偶尔还是有个别剧会取父父级的标题.
![image](https://github.com/FleyX/open-renamer/assets/49450669/e87c12e5-aa90-4102-a3df-aaa1ae3dfc46)
![image](https://github.com/FleyX/open-renamer/assets/49450669/ae7fc789-5a5c-4c83-bd54-55f85794b226)

**Comment by 277383761** [comment]
比如这张截图中的,有些是用的父级标题,有些却用的是父父级标题
![image](https://github.com/FleyX/open-renamer/assets/49450669/8e9feae1-e56a-4b3e-9675-ba4afbae5210)

**Comment by FleyX** [comment]
因为后台自动将中文的一到十作为了季号，就识别为剧集了
