### ISSUE TITLE
能否增加繁体简体中文互转的功能？

### ISSUE THREAD

**Issue by chrisdong** [FleyX/open-renamer#38]
参考一下 music tag web的批量转换音乐标签的功能
参考一下 advanced renamer 一类的 批量重命名软件，可以导入更多规则
增加 简体繁体转换还是有用的，很多 文件名原版是 繁体，有时候方便搜索，有必要改成简体中文，虽然有很多 Windows电脑版的软件，但是如果有一个 docker版的话，直接可以批量转换 nas存的文件名称，中文简繁体互转

希望这个软件 重命名的范围更广

**Comment by FleyX** [comment]
可以的

**Comment by chrisdong** [comment]
我用过好多简体繁体转换的软件，包括 chrome版，发现 这个https://microsoftedge.microsoft.com/addons/detail/ijddgmclgedepadbikmfekambhhfjfnl 转换 是正确的，不知道这个chrome插件用的是哪个api。其他的软件总有些字繁转简出现错误。 比如 繁体的 讃 转成简体时候，还是 讃。 但 newtongwen能 转成 赞

**Comment by chrisdong** [comment]
> 可以的

![hg1e5kju en2](https://github.com/FleyX/open-renamer/assets/3366796/498b3d6a-39be-4f06-9880-424faff7ee15)

music tag web 不仅能改 音源标签内的 简繁，还能 音频文件名的繁体简体

**Comment by FleyX** [comment]
更新到1.7.1版本即可。支持文件名简繁转换

**Comment by chrisdong** [comment]
> 可以的

感谢更新！
