### ISSUE TITLE
又是我,希望模板可以移动位置上下排序

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#4]
可能有洁癖吧,模板上下排序整齐一些

**Comment by FleyX** [comment]
什么意思，下面的模板列表排序？
![image](https://user-images.githubusercontent.com/29558551/165668859-eedadb2f-c23e-4838-a751-eaaea9c3eed8.png)

**Comment by 277383761** [comment]
是的,就是模板可以随便移动上下位置,是的.是的.

**Comment by FleyX** [comment]
考虑到模板不会有太多，不会实现这些功能
