### ISSUE TITLE
好东西 终于找到这种了  就是能支持正则就好了

### ISSUE THREAD

**Issue by a872675986** [FleyX/open-renamer#40]

**Comment by FleyX** [comment]
可以的，好几个人都提到正则了，下个版本将会支持js正则

**Comment by FleyX** [comment]
删除，替换规则已增加正则支持。升级到1.8.0即可

**Comment by a872675986** [comment]
> 删除，替换规则已增加则支持。升级到1.8.0即可

docker的没升级吗 我怎么指定新版还是1.80的 底下都还是显示1.71呢 大佬 然后也没发现正则功能
