### ISSUE TITLE
docker的没升级吗 我怎么指定新版本还是1.80的底下都还是显示1.71呢大佬然后也没发现正则功能

### ISSUE THREAD

**Issue by a872675986** [FleyX/open-renamer#41]

**Comment by FleyX** [comment]
> _No description provided._

打镜像忘了更新代码，现在好了。重新拉取1.8.0即可

**Comment by a872675986** [comment]
> > _未提供描述。_
> 
> 打镜像忘了更新代码，现在好了。重新拉取1.8.0即可

感谢 目前正常了
