### ISSUE TITLE
你好,这个季号识别是肿么使用的啊

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#6]
我不知道如何使用这个季号识别.与期望的不一样.哈哈

我希望的是比如我的磁盘下载文件夹内有
权力的游戏/S1/第一集或者权力游戏01集.mp4
权力的游戏/S1/第二集或者权力游戏02集.mp4
权力的游戏/S1/第三集或者权力游戏03集.mp4
权力的游戏/S1/第四集或者权力游戏04集.mp4

如上可以一键批量命名成如下

权力的游戏/S1/S1E01.mp4
权力的游戏/S1/S1E02.mp4
权力的游戏/S1/S1E03.mp4
权力的游戏/S1/S1E04.mp4

上面是单季的表达,接下来还有S2与S3至S8或Sn季
权力的游戏/S1/S1E01.mp4   S1E02.mp4  S1E03.mp4
权力的游戏/S2/S2E01.mp4  ....
权力的游戏/S3/S3E01.mp4   ....

现在希望的是能检测整个目录,只要发现带有S1 S2 S3这些文件夹名的内部的文件自动批量命名成如上这样S1E01.mp4 ....

我也不知道说清楚了没有.哈哈.意思差不多想表达的就是更智能一些,直接检测整个文件夹.

上面的功能倒是其次的,因为我创建了n份模板,问题不大了.只是麻烦一点而已.

暂时有一个比较急的功能.因为每次下载的目录都是固定的,所以希望能在新增文件的时候有一个记忆优先打开下载目录的选项.不用反复的点击从上级目录一级一级走到下载目录里才选择文件.虽然我知道可以用-v在docker中指定一条下载目录,可是我偶尔还会用你的工具去批量命名其它位置上的文件.所以我-v进去的是我的主目录级路径.不知道您能不能理解

**Comment by 277383761** [comment]
![截屏2022-05-10 下午3 53 33](https://user-images.githubusercontent.com/49450669/167577880-88bbf8ae-84e7-41d0-b259-18dfbb6a0a69.png)
![截屏2022-05-10 下午3 53 43](https://user-images.githubusercontent.com/49450669/167577915-78f10b97-2784-434d-84a3-bdc71aadd188.png)
![截屏2022-05-10 下午3 53 54](https://user-images.githubusercontent.com/49450669/167577929-56300f31-c159-48b9-bdc3-91b197c99fea.png)

**Comment by 277383761** [comment]
航拍中国 (2017)/S1/S1E01.mp4
........................./S2/S2E01.mp4
........................./S3/S3E01.mp4

S表示季,E表示集,S1E01表示第一季的第一集

**Comment by 277383761** [comment]
现在如果我下载了一部别人命名不是很规则的航拍中国三季全,我希望它能帮我自动检测一下,然后批量命名成如截图中内样.我是不是好啰嗦,哈哈

**Comment by FleyX** [comment]
![image](https://user-images.githubusercontent.com/29558551/167579177-62d8986c-6f22-4f42-87c0-f163a8fede96.png)
只是插入功能中加一个识别季号的开关，打开后会将文件所属文件夹名称中的季号提取出来放在后面
并不是一个全自动的按钮，还是需要选择文件，只是会自动识别出季号，不用手动改
你的需求可以用下面这样的通用模板实现
![image](https://user-images.githubusercontent.com/29558551/167579923-1d4bec28-61de-4334-b354-6998e66cff4e.png)

**Comment by FleyX** [comment]
整个目录全自动识别修改，不太可能开发。
新增文件默认打开某个目录，可以开发。

**Comment by 277383761** [comment]
![截屏2022-05-10 下午4 13 45](https://user-images.githubusercontent.com/49450669/167581602-11aa0985-1cc2-4d87-b0c7-d39eb23e5514.png)
关于季的批量问题跳过了,因为我自己手动创建了N个模板效率也很高.
那您就做一个新增文件时的额外目录按钮.放在主页面,比如收藏当前目录新增一个按钮出来,下次可以迅速点击直达下载目录

**Comment by FleyX** [comment]
预计开发功能如图：增加一个收藏按钮，同时可设置为新增文件打开默认显示路径
![image](https://user-images.githubusercontent.com/29558551/167583174-e8cbd4a2-6f44-452c-8277-41ac7f96c2c8.png)

**Comment by 277383761** [comment]
YYDS

**Comment by FleyX** [comment]
对了，能问下你是怎么找资源的？
我主要是在这里[https://btbtt12.com/](https://btbtt12.com/)找的

**Comment by 277383761** [comment]
我是在阿里小站上找的.https://www.pan666.cn/t/video?sort=newest

**Comment by 277383761** [comment]
我建议收藏路径不要在二级菜单,直接在主页面更有效率.顺便收藏目录可以命名成自己喜欢的名字.哈哈

**Comment by FleyX** [comment]
可以的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月10日 17:32
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [FleyX/open-renamer] 你好,这个季号识别是肿么使用的啊 (Issue #6)


我建议收藏路径不要在二级菜单,直接在主页面更有效率.顺便收藏目录可以命名成自己喜欢的名字.哈哈

―

**Comment by 277383761** [comment]
我又来啰嗦了,希望常用的几个模板也可以在一级主页显示,自定义须要显示的几个模板.点击即可,更有效率.还有手机页面适配的好像不是非常棒

**Comment by 277383761** [comment]
我特地测试了一下你说的季识别功能,不错不错,原本要创建n个模板,压缩到了只用两个模板.感谢.

**Comment by 277383761** [comment]
既然可以做到这样的功能了,对你来说应该很容易完成后面的事了,把01.mp4修改为S1E01.mp4这类骚操作.希望你来完成,是因为如果有第一集到50集的视频,我的用模板的方法是按顺序来的,如果缺少了某一集,就会变成23.mp4被修改成了S1E22.mp4,所有都对不齐了.而带智能检测识别的话.就不会发生这样的事

**Comment by 277383761** [comment]
这个季识别功能,如果我想保留原文件名的话,在之前创建<S1E1-原文件名.mp4>无法实现,会变成<SE1-原文件名1.mp4>

**Comment by 277383761** [comment]
只能实现成<原文件名-S1E1.mp4> 行吧,就这样也可以了.

**Comment by FleyX** [comment]
有bug，有空我改下

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月11日 10:27
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [FleyX/open-renamer] 你好,这个季号识别是肿么使用的啊 (Issue #6)


只能实现成<原文件名-S1E1.mp4> 行吧,就这样也可以了.

―

**Comment by FleyX** [comment]
bug已修复，切换到0.8版本
