### ISSUE TITLE
对了,又是我,有一件很重要的事

### ISSUE THREAD

**Issue by 277383761** [FleyX/open-renamer#7]
有时候是远程nas批量命名的.开放着端口号的.
如果没有加密会很危险.建议弄个密码.但又不想每天刷新页面使用的时候都要输入一次密码.会很麻烦.
您觉得有没有必要加密?
不然别人扫到此端口,胡搞瞎搞,所有媒体的资料就被命名成不知啥样的了.

**Comment by FleyX** [comment]
不要暴露此端口，如果需要远程访问可以用ssh进行转口转发


在 2022年5月14日，09:48，277383761 ***@***.***> 写道：

﻿

有时候是远程nas批量命名的.开放着端口号的.
如果没有加密会很危险.建议弄个密码.但又不想每天刷新页面使用的时候都要输入一次密码.会很麻烦.
您觉得有没有必要加密?
不然别人扫到此端口,胡搞瞎搞,所有媒体的资料就被命名成不知啥样的了.

**Comment by FleyX** [comment]
可以

在 2022年5月16日，09:51，277383761 ***@***.***> 写道：

﻿

能不能做一个登陆时的密码.然后在浏览器缓存内,只要不是换一台新电脑登陆都无须重新输入密码.
